module.exports = {
    CURRENT_MAIN_NAVIGATION_ITEM_CHANGED: 1,
    BOX_FILTER_UPDATED: 2,
    PLAYLIST_CREATED: 3,
    CURRENT_PLAYLIST_CHANGED: 4,
    PLAYLIST_TRACKS_UPDATED: 5,
    CURRENT_TRACK_CHANGED: 6
};